version: '3.8'

services:
  postgres:
    build: .  # Usa o Dockerfile do diretório atual
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistência de dados

volumes:
  postgres_data:  # Volume para persistir dados mesmo se o container for removido